import { company, whatsappUrl } from '../config/company';
import { services } from '../data/services';
import HouseVisual from '../components/HouseVisual';
import Icon from '../components/Icon';
import QuoteForm from '../components/QuoteForm';
import { ServicesSection, AboutSection, WhyChooseUs, SolarHighlight, ProcessSection, CTASection } from '../components/Sections';
export function Home() { return <><section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="tiny-line"/> ELECTRICAL & SOLAR SOLUTIONS</p><h1>Powering homes.<br/><span>Connecting lives.</span></h1><p>Reliable electrical solutions for the place that matters most. From house wiring to solar power, let’s make your home work better.</p><div className="hero-buttons"><a className="button" href="/contact#quote">Request a quote <Icon name="arrow"/></a><a className="button secondary" href="#services">Explore our services</a></div><div className="hero-promise"><Icon name="shield"/><span>Careful workmanship. Practical solutions.</span></div></div><HouseVisual/></div><div className="container hero-bottom"><span>YOUR HOME. OUR FOCUS.</span><div><span>House wiring</span><i/><span>Solar installations</span><i/><span>Distribution boards</span><i/><span>Maintenance</span></div></div></section><ServicesSection/><AboutSection/><WhyChooseUs/><SolarHighlight/><ProcessSection/><CTASection/><QuoteSection/></>; }
export function QuoteSection({ initialService = '' }) { return <section className="section container quote-section" id="quote"><div><p className="eyebrow">TELL US WHAT YOU NEED</p><h2>A better-powered<br/>home starts here.</h2><p>Planning something new or need a hand with an electrical problem? Share a few details about your project.</p><div className="quote-aside"><Icon name="chat"/><p>No need to have all the answers.<br/>Start with what you have in mind.</p></div></div><QuoteForm initialService={initialService}/></section>; }
export function PageHero({ eyebrow, title, children }) { return <section className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{children}</p></div></section>; }
export function About() { return <><PageHero eyebrow="ABOUT RAMUNUSI HOLDINGS" title="Focused on your home.">Residential electrical services with a practical, considered approach.</PageHero><AboutSection/><WhyChooseUs/><ProcessSection/><CTASection/></>; }
export function Services() { return <><PageHero eyebrow="OUR SERVICES" title="Everyday needs. Expert attention.">Electrical installations, maintenance and solar solutions for your home.</PageHero><ServicesSection/><ProcessSection/><CTASection/></>; }
export function ServicePage({ service }) { return <><PageHero eyebrow="RESIDENTIAL ELECTRICAL SERVICES" title={service.title}>{service.intro}</PageHero><section className="section container service-detail"><div><a className="text-link" href="/services">← All services</a><h2>A solution built around your needs.</h2><p>{service.overview}</p><a className="button" href={`/contact?service=${service.slug}#quote`}>{service.slug === 'solar-installation' ? 'Get a solar installation quote' : 'Request a quote'}<Icon name="arrow"/></a></div><div className="work-list"><Icon name={service.icon}/><h2>How we can help</h2><ul>{service.work.map(work => <li key={work}><Icon name="check"/>{work}</li>)}</ul></div></section>{service.slug === 'solar-installation' && <section className="section solar-explained"><div className="container"><p className="eyebrow">UNDERSTANDING YOUR SYSTEM</p><h2>Four parts. One connected home.</h2><div className="trust-grid">{[['Solar panels','Panels generate electricity from sunlight. Output varies with sunlight, placement and system size.'],['Inverter','The inverter converts and manages electricity so it can be used by your household.'],['Battery storage','Batteries store electricity for use when solar generation is unavailable or during interruptions, within the system’s capacity.'],['Complete integration','Panels, inverter and batteries can work together with your existing household electrical installation.']].map(([title,copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>}<WhyChooseUs/><CTASection/></>; }
export function Contact({ initialService }) { return <><PageHero eyebrow="CONTACT US" title="Let’s talk about your home.">A new installation, an upgrade or a repair. It all starts with a conversation.</PageHero><section className="container contact-details" id="contact-details">{[['Phone',company.phone,company.phone ? `tel:${company.phone.replace(/\s/g,'')}` : null],['WhatsApp',company.whatsapp,whatsappUrl],['Email',company.email,company.email ? `mailto:${company.email}` : null],['Service area',company.serviceArea],['Operating hours',company.hours]].map(([label,value,href]) => <div key={label}><h2>{label}</h2>{value ? (href ? <a href={href}>{value}</a> : <p>{value}</p>) : <p>To be confirmed</p>}</div>)}</section><QuoteSection initialService={initialService}/></>; }
export function NotFound() { return <PageHero eyebrow="404 · PAGE NOT FOUND" title="Let’s get you connected."><a className="text-link" href="/">Return to the homepage →</a></PageHero>; }
