import { useEffect, useState } from 'react';
import { services } from '../data/services';
import { validateQuote, submitQuote } from '../lib/quote';
import Icon from './Icon';
export default function QuoteForm({ initialService = '' }) {
  const [selectedService, setSelectedService] = useState('');
  useEffect(() => setSelectedService(initialService), [initialService]);
  const [errors,setErrors] = useState({}); const [status,setStatus] = useState({kind:'idle',message:''});
  async function handleSubmit(event) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); const nextErrors = validateQuote(values); setErrors(nextErrors); if (Object.keys(nextErrors).length) { form.elements[Object.keys(nextErrors)[0]].focus(); return; } setStatus({kind:'sending',message:''}); try { await submitQuote(values,import.meta.env.VITE_QUOTE_ENDPOINT); setStatus({kind:'success',message:'Thank you. Your quote request has been sent to Ramunusi Holdings.'}); form.reset(); setSelectedService(initialService); } catch(error) { setStatus({kind:'error',message:error.name === 'TimeoutError' ? 'The request timed out. Please try again.' : error.message}); } }
  const field = (name,label,type='text',placeholder='') => <div className="field"><label htmlFor={name}>{label} <span>*</span></label><input id={name} name={name} type={type} placeholder={placeholder} required maxLength={200} autoComplete={{name:'name',phone:'tel',email:'email',area:'address-level2'}[name]} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `${name}-error` : undefined}/>{errors[name] && <span className="field-error" id={`${name}-error`}>{errors[name]}</span>}</div>;
  return <form className="quote-form" onSubmit={handleSubmit} noValidate><div className="form-grid">{field('name','Full name','text','Your full name')}{field('phone','Phone number','tel','Your contact number')}{field('email','Email address','email','you@example.com')}<div className="field"><label htmlFor="service">Service required <span>*</span></label><select id="service" name="service" value={selectedService} onChange={event => setSelectedService(event.target.value)} required aria-invalid={!!errors.service} aria-describedby={errors.service ? 'service-error' : undefined}><option value="">Select a service</option>{services.map(s=><option key={s.slug} value={s.slug}>{s.title}</option>)}<option value="other">Other</option></select>{errors.service && <span className="field-error" id="service-error">{errors.service}</span>}</div><div className="full-width">{field('area','Property / area','text','Suburb, town or property location')}</div><div className="field full-width"><label htmlFor="description">Tell us about your project <span>*</span></label><textarea id="description" name="description" rows="4" maxLength={5000} placeholder="Please briefly describe the electrical work you need assistance with." required aria-invalid={!!errors.description} aria-describedby={errors.description ? 'description-error' : undefined}/>{errors.description && <span className="field-error" id="description-error">{errors.description}</span>}</div></div><p className="form-note">All fields are required. We’ll use your details to respond to your enquiry.</p>{!import.meta.env.VITE_QUOTE_ENDPOINT && <p className="setup-note">Online quote requests are being set up. This form cannot send enquiries yet.</p>}<button className="button" type="submit" disabled={status.kind === 'sending'}>{status.kind === 'sending' ? 'Sending…' : 'Request quote'}<Icon name="arrow"/></button><div aria-live="polite" role="status" className={`form-status ${status.kind}`}>{status.message}</div></form>;
}
