import { services } from '../data/services';
import Icon from './Icon';
export function SectionHeading({ eyebrow, title, children }) { return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children && <p>{children}</p>}</div>; }
export function ServicesSection() { return <section className="section container" id="services"><SectionHeading eyebrow="WHAT WE DO" title="The right solution. Every connection.">From a new light fitting to a complete solar installation, we help keep your home connected.</SectionHeading><div className="service-grid">{services.map((s,i) => <article className="service-card" key={s.slug}><div className="card-top"><Icon name={s.icon}/><span>0{i+1}</span></div><h3>{s.short}</h3><p>{s.description}</p><a href={`/services/${s.slug}`}>Explore service <Icon name="arrow"/><span className="sr-only">: {s.title}</span></a></article>)}</div></section>; }
export function AboutSection() { return <section className="about-section section"><div className="container about-grid"><div><p className="eyebrow">A LITTLE ABOUT US</p><h2>Good work starts with<br/>understanding your home.</h2></div><div><p className="large-copy">Practical solutions. Careful workmanship. Clear communication.</p><p>Ramunusi Holdings provides residential electrical services focused on safe, reliable and practical solutions. We assist homeowners with domestic wiring, solar systems, distribution boards and electrical maintenance.</p><a className="text-link" href="/about">Get to know Ramunusi <Icon name="arrow"/></a></div></div></section>; }
export function WhyChooseUs() { const points = [['shield','Safety focused','Care and attention at every connection.'],['tool','Quality workmanship','A considered approach to your electrical work.'],['check','Reliable service','Clear communication, from enquiry to next steps.'],['home','Practical solutions','Work shaped around your home and its needs.']]; return <section className="section container"><SectionHeading eyebrow="THE RAMUNUSI APPROACH" title="Small details. A real difference."/><div className="trust-grid">{points.map(([icon,title,copy]) => <article key={title}><Icon name={icon}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>; }
export function SolarHighlight() { return <section className="container solar-highlight"><div className="solar-art" aria-hidden="true"><div className="sun-orbit"><Icon name="sun"/></div><div className="panel-grid">{Array.from({length:12},(_,i) => <span key={i}/>)}</div><span className="solar-art-label">A BRIGHTER WAY TO POWER YOUR HOME</span></div><div><p className="eyebrow">MAKE ROOM FOR SOLAR</p><h2>More sunshine.<br/>More possibilities.</h2><p>Bring solar panels, an inverter and battery storage together in a system that works with your home and your power needs.</p><a className="button" href="/services/solar-installation">Discover our solar solutions <Icon name="arrow"/></a></div></section>; }
export function ProcessSection() { return <section className="section container"><SectionHeading eyebrow="HOW IT WORKS" title="Let’s make it simple."/><div className="process-grid">{[['Contact us','Tell us about your home and the electrical work you have in mind.'],['Talk through the details','We discuss your requirements and outline the next steps or quotation.'],['Get the work underway','Arrange the installation or repair, with clear communication along the way.']].map(([title,copy],i) => <article key={title}><span className="step">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>; }
export function CTASection() { return <section className="cta-section"><div className="container"><div><p className="eyebrow">LET’S GET STARTED</p><h2>Your next project starts<br/>with a conversation.</h2></div><a className="button" href="/contact#quote">Request a quote <Icon name="arrow"/></a></div></section>; }
